### ISSUE TITLE
Task Templates not showing

### ISSUE THREAD

**Issue by yeahmoin** [helpwave/web#712] opened 2023-09-04 11:50 UTC
## Issue
Templates not working for me at all
- Personal nor Ward templates
- all templates missing in my Templates sidebar, when adding new tasks
- they do appear, when I am in settings

## Expected behaviour
- Add template(s) personal or ward and save
- add new task to patient and select former created template

## Actual behaviour
- templates missing

**Comment by DasProffi** [comment] 2023-10-06 09:29
@yeahmoin is this still a problem for you? The issue seems to be fixed in the current version. At least I was unable to reproduce this.

**Comment by use-to** [comment] 2023-10-16 07:57
> @yeahmoin is this still a problem for you? The issue seems to be fixed in the current version. At least I was unable to reproduce this.

I can't reproduce it anymore, too. @DasProffi Should we close this?

**Closed** 2023-10-16 08:19 UTC
Labels: bug, tasks
